// lib/municipal-data/scottsdale.ts
// Scottsdale, AZ Municipal Zoning Database

import type { ZoningDistrict } from './phoenix';

export const scottsdaleZoning: Record<string, ZoningDistrict> = {

  // Single-Family Residential
  "R1-190": {
    code: "R1-190",
    name: "Single-Family Residential (190,000 sf)",
    description: "Very low density, large estate lots",
    minLotSize: 190000,
    maxLotCoverage: 20,
    maxBuildingHeight: 24,
    setbacks: {
      front: 50,
      rear: 50,
      side: 35,
      streetSide: 50,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 50, rear: 10, side: 10, streetSide: 30 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
      notes: ["Guest house provisions apply"],
    },
    pool: {
      setbackFromProperty: 10,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 25,
      setbackRear: 10,
      setbackSide: 10,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-70": {
    code: "R1-70",
    name: "Single-Family Residential (70,000 sf)",
    description: "Low density estate lots",
    minLotSize: 70000,
    maxLotCoverage: 25,
    maxBuildingHeight: 24,
    setbacks: {
      front: 40,
      rear: 40,
      side: 25,
      streetSide: 40,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 40, rear: 10, side: 10, streetSide: 25 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
    },
    pool: {
      setbackFromProperty: 10,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 25,
      setbackRear: 10,
      setbackSide: 10,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-43": {
    code: "R1-43",
    name: "Single-Family Residential (43,560 sf / 1 acre)",
    description: "One acre minimum lots",
    minLotSize: 43560,
    maxLotCoverage: 30,
    maxBuildingHeight: 24,
    setbacks: {
      front: 35,
      rear: 35,
      side: 20,
      streetSide: 35,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 35, rear: 10, side: 10, streetSide: 20 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
    },
    pool: {
      setbackFromProperty: 6,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 25,
      setbackRear: 10,
      setbackSide: 10,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-35": {
    code: "R1-35",
    name: "Single-Family Residential (35,000 sf)",
    description: "Large lot single-family",
    minLotSize: 35000,
    maxLotCoverage: 30,
    maxBuildingHeight: 24,
    setbacks: {
      front: 30,
      rear: 30,
      side: 15,
      streetSide: 30,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 30, rear: 10, side: 10, streetSide: 15 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
    },
    pool: {
      setbackFromProperty: 6,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 25,
      setbackRear: 10,
      setbackSide: 10,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-18": {
    code: "R1-18",
    name: "Single-Family Residential (18,000 sf)",
    description: "Medium-large lot single-family",
    minLotSize: 18000,
    maxLotCoverage: 35,
    maxBuildingHeight: 24,
    setbacks: {
      front: 25,
      rear: 25,
      side: 10,
      streetSide: 25,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 25, rear: 10, side: 5, streetSide: 15 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
    },
    pool: {
      setbackFromProperty: 5,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 20,
      setbackRear: 5,
      setbackSide: 5,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-10": {
    code: "R1-10",
    name: "Single-Family Residential (10,000 sf)",
    description: "Standard single-family",
    minLotSize: 10000,
    maxLotCoverage: 40,
    maxBuildingHeight: 24,
    setbacks: {
      front: 20,
      rear: 20,
      side: 5,
      streetSide: 15,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 1000,
      minLotSizeSqFt: 7000,
      setbacks: { front: 20, rear: 5, side: 5, streetSide: 15 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 24,
      notes: ["Scottsdale requires 7,000 sf minimum for ADU"],
    },
    pool: {
      setbackFromProperty: 5,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 20,
      setbackRear: 5,
      setbackSide: 5,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-7": {
    code: "R1-7",
    name: "Single-Family Residential (7,000 sf)",
    description: "Smaller lot single-family",
    minLotSize: 7000,
    maxLotCoverage: 45,
    maxBuildingHeight: 24,
    setbacks: {
      front: 20,
      rear: 15,
      side: 5,
      streetSide: 15,
    },
    adu: {
      allowed: true,
      maxSizeSqFt: 850,
      minLotSizeSqFt: 7000,
      setbacks: { front: 20, rear: 5, side: 5, streetSide: 15 },
      parking: 1,
      requiresOwnerOccupancy: false,
      maxHeight: 20,
      notes: ["Reduced ADU size for smaller lots"],
    },
    pool: {
      setbackFromProperty: 5,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 20,
      setbackRear: 5,
      setbackSide: 3,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R1-5": {
    code: "R1-5",
    name: "Single-Family Residential (5,000 sf)",
    description: "High-density single-family",
    minLotSize: 5000,
    maxLotCoverage: 50,
    maxBuildingHeight: 24,
    setbacks: {
      front: 15,
      rear: 15,
      side: 5,
      streetSide: 10,
    },
    adu: {
      allowed: false,
      maxSizeSqFt: 0,
      minLotSizeSqFt: 7000,
      setbacks: { front: 0, rear: 0, side: 0 },
      parking: 0,
      requiresOwnerOccupancy: false,
      notes: ["Lot too small for ADU (7,000 sf minimum required)"],
    },
    pool: {
      setbackFromProperty: 5,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 15,
      setbackRear: 5,
      setbackSide: 3,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  // Multi-Family
  "R-3": {
    code: "R-3",
    name: "Multi-Family Residential",
    description: "Apartments and townhomes",
    minLotSize: 7000,
    maxLotCoverage: 50,
    maxBuildingHeight: 36,
    setbacks: {
      front: 25,
      rear: 20,
      side: 10,
      streetSide: 15,
    },
    adu: {
      allowed: false,
      maxSizeSqFt: 0,
      minLotSizeSqFt: 0,
      setbacks: { front: 0, rear: 0, side: 0 },
      parking: 0,
      requiresOwnerOccupancy: false,
      notes: ["ADUs not applicable to multi-family"],
    },
    pool: {
      setbackFromProperty: 10,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 20,
      setbackRear: 10,
      setbackSide: 10,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R-4": {
    code: "R-4",
    name: "Multi-Family Residential (Medium Density)",
    description: "Medium-density apartments",
    minLotSize: 10000,
    maxLotCoverage: 55,
    maxBuildingHeight: 48,
    setbacks: {
      front: 25,
      rear: 25,
      side: 15,
      streetSide: 20,
    },
    adu: {
      allowed: false,
      maxSizeSqFt: 0,
      minLotSizeSqFt: 0,
      setbacks: { front: 0, rear: 0, side: 0 },
      parking: 0,
      requiresOwnerOccupancy: false,
    },
    pool: {
      setbackFromProperty: 10,
      setbackFromHouse: 6,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 25,
      setbackRear: 10,
      setbackSide: 15,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },

  "R-5": {
    code: "R-5",
    name: "Multi-Family Residential (High Density)",
    description: "High-density residential",
    minLotSize: 15000,
    maxLotCoverage: 60,
    maxBuildingHeight: 72,
    setbacks: {
      front: 30,
      rear: 30,
      side: 20,
      streetSide: 25,
    },
    adu: {
      allowed: false,
      maxSizeSqFt: 0,
      minLotSizeSqFt: 0,
      setbacks: { front: 0, rear: 0, side: 0 },
      parking: 0,
      requiresOwnerOccupancy: false,
    },
    pool: {
      setbackFromProperty: 15,
      setbackFromHouse: 10,
      requiresFence: true,
      fenceHeight: 5,
      permitRequired: true,
    },
    garage: {
      setbackFront: 30,
      setbackRear: 15,
      setbackSide: 20,
      maxHeightDetached: 15,
    },
    permits: {
      buildingExemptUnder: 200,
      electricalAlwaysRequired: true,
      plumbingAlwaysRequired: true,
      reroof: false,
      hvacChangeout: false,
      waterHeater: false,
    },
  },
};

// Helper function
export function getZoningByCode(code: string): ZoningDistrict | null {
  const normalizedCode = code.toUpperCase().replace(/\s+/g, '');
  return scottsdaleZoning[normalizedCode] || null;
}

export default scottsdaleZoning;
